// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_B5yZ8FqQ__GtZi4EVUFceOgV02lqrGM',
    appId: '1:438474764656:web:3c75d44c41ab3b22f7dfb5',
    messagingSenderId: '438474764656',
    projectId: 'uangin-ppti11',
    authDomain: 'uangin-ppti11.firebaseapp.com',
    storageBucket: 'uangin-ppti11.appspot.com',
    measurementId: 'G-4Q6CPF1BYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAGG3oZPU5xLunUi-rno3pqtW3uJqenXA',
    appId: '1:438474764656:android:9f6a39df916822f2f7dfb5',
    messagingSenderId: '438474764656',
    projectId: 'uangin-ppti11',
    storageBucket: 'uangin-ppti11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9ISiVLkuvrySOZn7fLWkcN_MLNdF5SYE',
    appId: '1:438474764656:ios:6068ae93ca153189f7dfb5',
    messagingSenderId: '438474764656',
    projectId: 'uangin-ppti11',
    storageBucket: 'uangin-ppti11.appspot.com',
    iosClientId: '438474764656-isp1nog8q1k8ud1njrijruttdsgccs4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.uangin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9ISiVLkuvrySOZn7fLWkcN_MLNdF5SYE',
    appId: '1:438474764656:ios:6068ae93ca153189f7dfb5',
    messagingSenderId: '438474764656',
    projectId: 'uangin-ppti11',
    storageBucket: 'uangin-ppti11.appspot.com',
    iosClientId: '438474764656-isp1nog8q1k8ud1njrijruttdsgccs4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.uangin',
  );
}
